# Generated by Django 2.0.1 on 2018-01-23 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0009_auto_20180116_1816'),
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=2000)),
                ('coin_symbol', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_denominator', models.CharField(max_length=200)),
                ('order_type', models.CharField(max_length=400)),
                ('order_status', models.CharField(blank=True, max_length=600)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.PeriodData')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='period',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
