# Generated by Django 2.0.1 on 2018-01-23 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_auto_20180122_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='allorders',
            name='unique_id',
            field=models.CharField(default=datetime.datetime(2018, 1, 23, 3, 41, 14, 26724, tzinfo=utc), max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allorders',
            name='order_type',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
