# Generated by Django 2.0.1 on 2018-01-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0002_capitalavailable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_pair', models.CharField(max_length=200, unique=True)),
                ('min_quantity', models.FloatField()),
                ('max_quantity', models.FloatField()),
                ('step_size', models.FloatField()),
            ],
        ),
    ]
