# Generated by Django 2.0.1 on 2018-01-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('num_sell_orders', models.IntegerField()),
                ('num_buy_orders', models.IntegerField()),
                ('val_sell_orders', models.FloatField()),
                ('val_buy_orders', models.FloatField()),
                ('largest_sell_order_quantity', models.FloatField()),
                ('largest_sell_order_value', models.FloatField()),
                ('largest_buy_order_quantity', models.FloatField()),
                ('largest_buy_order_value', models.FloatField()),
                ('crypto_pairs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.CryptoPairs')),
            ],
        ),
        migrations.AddField(
            model_name='cryptopairs',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.Dates'),
        ),
    ]
