# Generated by Django 2.0.1 on 2018-01-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('timestamp', models.CharField(max_length=3000)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('fill_type', models.CharField(max_length=300)),
                ('order_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='dates',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='perioddata',
            old_name='crypto_pairs',
            new_name='crypto_pair',
        ),
        migrations.AddField(
            model_name='order',
            name='time_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.PeriodData'),
        ),
    ]
