# Generated by Django 2.0.1 on 2018-01-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0003_orderbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='ExecutedTrades',
        ),
        migrations.RenameModel(
            old_name='OrderBook',
            new_name='OrderBookEntry',
        ),
        migrations.AddField(
            model_name='perioddata',
            name='ask_price',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perioddata',
            name='bid_price',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perioddata',
            name='current_rate',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
