# Generated by Django 2.0.1 on 2018-01-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0004_auto_20180111_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executedtrades',
            name='order_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='executedtrades',
            name='price',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='executedtrades',
            name='quantity',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='executedtrades',
            name='total',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='perioddata',
            name='largest_buy_order_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='perioddata',
            name='largest_buy_order_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='perioddata',
            name='largest_sell_order_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='perioddata',
            name='largest_sell_order_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='perioddata',
            name='val_buy_orders',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='perioddata',
            name='val_sell_orders',
            field=models.FloatField(default=0),
        ),
    ]
