# Generated by Django 2.0.1 on 2018-01-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0005_auto_20180112_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbookentry',
            name='quantity',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='orderbookentry',
            name='rate',
            field=models.CharField(max_length=15),
        ),
    ]
