# Generated by Django 2.0.1 on 2018-01-12 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0006_auto_20180112_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='perioddata',
            name='start_timestamp',
            field=models.DateField(default=datetime.datetime(2018, 1, 12, 21, 4, 59, 323379)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perioddata',
            name='num_buy_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perioddata',
            name='num_sell_orders',
            field=models.IntegerField(default=0),
        ),
    ]
