# Generated by Django 2.0.1 on 2018-01-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0008_auto_20180112_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='perioddata',
            name='ask_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='perioddata',
            name='bid_quantity',
            field=models.FloatField(default=0),
        ),
    ]
