# Generated by Django 2.0.1 on 2018-01-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20180117_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodsignals',
            old_name='rate',
            new_name='price',
        ),
        migrations.AddField(
            model_name='periodsignals',
            name='fwdLong',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='periodsignals',
            name='fwdShort',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='periodsignals',
            name='param1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodsignals',
            name='param2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodsignals',
            name='param3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='periodsignals',
            name='action',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='periodsignals',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.CryptoPairs'),
        ),
        migrations.DeleteModel(
            name='CryptoPairs',
        ),
    ]
