# Generated by Django 2.0.1 on 2018-01-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_auto_20180117_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodsignals',
            name='period',
            field=models.IntegerField(unique=True),
        ),
    ]
