# Generated by Django 2.0.1 on 2018-01-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_auto_20180117_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodsignals',
            name='ideitifier',
            field=models.CharField(default='sd', max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodsignals',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='periodsignals',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
