# Generated by Django 2.0.1 on 2018-01-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_auto_20180117_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodsignals',
            old_name='ideitifier',
            new_name='identifier',
        ),
    ]
